=== FJrodafo/University/DAW/LND/XSL/T4_CDs/cds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="cds">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cd" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="artistas">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="artista" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="canciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="cancion" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="duracion" type="xs:time" use="required" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="sellos_discograficos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="sello_discografico" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="titulo_album" type="xs:string" use="required" />
                        <xs:attribute name="aÃ±o_publicacion" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FJrodafo/University/DAW/LND/XSL/T4_CDs/cds.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cds.xsl"?>
<cds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cds.xsd">
    <!-- CD1 -->
    <cd titulo_album="Nevermind" año_publicacion="1991">
        <artistas>
            <artista>Nirvana</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:05:01">Smells Like Teen Spirit</cancion>
            <cancion duracion="00:04:14">In Bloom</cancion>
            <cancion duracion="00:03:39">Come As You Are</cancion>
            <cancion duracion="00:03:03">Breed</cancion>
            <cancion duracion="00:04:17">Lithium</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>DGC Records</sello_discografico>
            <sello_discografico>Virgin Records</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD2 -->
    <cd titulo_album="Demon Days" año_publicacion="2005">
        <artistas>
            <artista>Nirvana</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:01:03">Intro</cancion>
            <cancion duracion="00:03:10">Last Living Souls</cancion>
            <cancion duracion="00:04:31">Kids With Guns</cancion>
            <cancion duracion="00:03:43">O Green World</cancion>
            <cancion duracion="00:04:53">Dirty Harry</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>Parlophone</sello_discografico>
            <sello_discografico>Virgin Records</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD3 -->
    <cd titulo_album="Goblin" año_publicacion="2011">
        <artistas>
            <artista>Tyler, The Creator</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:04:11">Goblin</cancion>
            <cancion duracion="00:07:18">Yonkers</cancion>
            <cancion duracion="00:04:13">Radicals</cancion>
            <cancion duracion="00:03:12">She</cancion>
            <cancion duracion="00:05:22">Transylvania</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>XL Recordings</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD4 -->
    <cd titulo_album="Madvillainy" año_publicacion="2004">
        <artistas>
            <artista>MF Doom</artista>
            <artista>Madlib</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:01:55">The Illest Villains</cancion>
            <cancion duracion="00:01:58">Accordion</cancion>
            <cancion duracion="00:02:11">Meat Grinder</cancion>
            <cancion duracion="00:02:35">Bistro</cancion>
            <cancion duracion="00:03:54">Raid</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>Stones Throw Records</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD5 -->
    <cd titulo_album="My Beautiful Dark Twisted Fantasy" año_publicacion="2010">
        <artistas>
            <artista>Kanye West</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:04:40">Dark Fantasy</cancion>
            <cancion duracion="00:05:57">Gorgeous</cancion>
            <cancion duracion="00:04:52">Power</cancion>
            <cancion duracion="00:01:02">All Of The Lights (Interlude)</cancion>
            <cancion duracion="00:04:59">All Of The Lights</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>Roc-A-Fella Records</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD6 -->
    <cd titulo_album="Random Access Memories" año_publicacion="2013">
        <artistas>
            <artista>Daft Punk</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:04:35">Give Life Back To Music</cancion>
            <cancion duracion="00:05:22">The Game Of Love</cancion>
            <cancion duracion="00:09:04">Giorgio By Moroder</cancion>
            <cancion duracion="00:03:48">Within</cancion>
            <cancion duracion="00:05:37">Instant Crush</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>Columbia</sello_discografico>
            <sello_discografico>Sony Music</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD7 -->
    <cd titulo_album="Good Kid, M.A.A.d City" año_publicacion="2012">
        <artistas>
            <artista>Kendrick Lamar</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:03:48">Sherane a.k.a Master Splinter's Daughter</cancion>
            <cancion duracion="00:05:37">Bitch, Don't Kill My Vibe</cancion>
            <cancion duracion="00:05:53">Backseat Freestyle</cancion>
            <cancion duracion="00:08:18">The Art Of Peer Pressure</cancion>
            <cancion duracion="00:06:09">Money Trees</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>Top Dawg Entertainment</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD8 -->
    <cd titulo_album="XX" año_publicacion="2009">
        <artistas>
            <artista>The XX</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:02:08">Intro</cancion>
            <cancion duracion="00:02:57">VCR</cancion>
            <cancion duracion="00:02:41">Crystalised</cancion>
            <cancion duracion="00:04:02">Islands</cancion>
            <cancion duracion="00:03:34">Heart Skipped A Beat</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>XL Recordings</sello_discografico>
            <sello_discografico>Young Turks</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD9 -->
    <cd titulo_album="The Suburbs" año_publicacion="2010">
        <artistas>
            <artista>Arcade Fire</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:05:15">The Suburbs</cancion>
            <cancion duracion="00:04:16">Ready To Start</cancion>
            <cancion duracion="00:04:40">Modern Man</cancion>
            <cancion duracion="00:03:57">Rococo</cancion>
            <cancion duracion="00:02:52">Empty Room</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>Merge Records</sello_discografico>
            <sello_discografico>Sonovox Records</sello_discografico>
        </sellos_discograficos>
    </cd>
    <!-- CD10 -->
    <cd titulo_album="In Rainbows" año_publicacion="2008">
        <artistas>
            <artista>Radiohead</artista>
        </artistas>
        <canciones>
            <cancion duracion="00:03:57">15 Step</cancion>
            <cancion duracion="00:04:02">Bodysnatchers</cancion>
            <cancion duracion="00:04:15">Nude</cancion>
            <cancion duracion="00:05:18">Weird Fishes/Arpeggi</cancion>
            <cancion duracion="00:03:49">All I Need</cancion>
        </canciones>
        <sellos_discograficos>
            <sello_discografico>TBD Records</sello_discografico>
            <sello_discografico>RED Distribution</sello_discografico>
            <sello_discografico>Virgin Records</sello_discografico>
        </sellos_discograficos>
    </cd>
</cds>
